Scrap rebalance & roof slopes
Aussieforks/steel pull request #1
Opened 2023-01-13 16:15 UTC by Maverick2797

Noticed a lack of configurability provided by the raillike roofing nodes, so added moreblocks slopes and panels to provide roof peaks, valleys and walls.
Happened to notice recipe conflicts at the same time with items from MTG, so added technic compatibility to fix too.
Technic ore processing happened to introduce an infinite iron exploit, so scrap return had to be reduced to compensate.

2023-01-15 06:54 UTC, Montandalar commented
- When cut with the circular saw, the leftovers are `steel_micro_roofing_bottom` but that is not a registered node.
- The steel roofing nodes and their circular saw shapes sound like leaves instead of like steel blocks or steel doors (wrought blocks they are called in technic). On AF they sound like stone, which isn't correct either. This is probably related to engine defaults for node groups. Stairsplus should let you choose which sounds to use, or at least it should hopefully match the base node.
- Some typos are present like racycling, recyling and compatability
- ~~Can't rotate it with the screwdriver~~ solution is to use moreblocks nodes if needs be
- I'd like to fix the collision box too:
```
diff --git a/nodes.lua b/nodes.lua
index 9812cf9..c6a2558 100644
--- a/nodes.lua
+++ b/nodes.lua
@@ -59,6 +59,11 @@ minetest.register_node("steel:grate_hard", {
        groups = {cracky = 1, choppy = 1, dig_stone = 1},
 })
 
+local roof_box = {
+       type = "fixed",
+       fixed = {-1/2, -1/2, -1/2, 1/2, -1/2+1/16, 1/2},
+}
+
 minetest.register_node("steel:roofing", {
        description = "Corrugated steel roofing",
        drawtype = "raillike",
@@ -67,14 +72,12 @@ minetest.register_node("steel:roofing", {
        wield_image = "steel_corrugated_steel.png",
        paramtype = "light",
        walkable = true,
-       selection_box = {
-               type = "fixed",
-               fixed = {-1/2, -1/2, -1/2, 1/2, -1/2+1/16, 1/2},
-       },
+       collision_box = roof_box,
+       selection_box = roof_box,
        groups = {bendy = 2, snappy = 1, dig_immediate = 2, dig_generic = 1},
 })
```

2023-01-15 06:55 UTC, Montandalar requested changes
See above comment

2023-01-31 12:02 UTC, closed without merging

2023-01-31 12:35 UTC, Maverick2797 commented
Renaming the branch due to the & having issues with bash. Will reopen and continue this thread in the new PR/branch

2023-01-31 13:41 UTC, Montandalar commented
quote your & (ampersands) with `'single quotes'` in bash to make it pass through verbatim (but yeah, generally ampersands in a branch name are a bad idea)